In [2]:
a=12

In [3]:
print(a)

12


In [4]:
def hello():
    print("hello how are you")

In [5]:
hello()

hello how are you


In [6]:
# python does not had array therefore we get numpy
# numeric and numarray combine to give numpy
# written in C
# compiled and super fast


In [7]:
# array v/s list
# array is homogeneous(one datatype)
# list is heterogeneous(multiple datatypes)
# list slow
# array is fast as written in C compile type 
# List more memory
# array less memory
# vector operations in array is faster than list



In [8]:
import numpy as np

### Basic array creation


In [9]:
arr = np.array([1,2,3,4])

In [10]:
print(arr)

[1 2 3 4]


In [11]:
a=[1,2,3,4,5,"hello"]

In [12]:
np.array(a)
# convert everything to string
# if no string and float convert everything to float

array(['1', '2', '3', '4', '5', 'hello'], dtype='<U21')

In [13]:
b = [1,2,3.5]

In [14]:
np.array(b)

array([1. , 2. , 3.5])

In [15]:
# no 2 dimentional list whereas we have 2 dimentional array

In [16]:
 l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [17]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
# above 2 dimentional array is tensor

### Array generation functions

In [19]:
np.arange(1,11) 
# array from 1 to 10

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
# zeros array
arr = np.zeros(6)# 6 zeros in a row
arr

array([0., 0., 0., 0., 0., 0.])

In [22]:
# multi dim zeros array
arr = np.zeros((4,8))
arr
# ((rows,cols))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [23]:
# unit matrix
arr = np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [24]:
arr = np.linspace(1,5,2) #linear space
arr
# same space between elements in between 1 and 5 we need to get 2 elements therefore 1 
# and 5

array([1., 5.])

In [25]:
arr = np.linspace(1,5,3)
arr
#array([1., 3., 5.])

array([1., 3., 5.])

In [26]:
arr = np.linspace(1,5,4)
arr
#array([1.        , 2.33333333, 3.66666667, 5.        ])

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [27]:
arr = np.linspace(0,1,100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

### Random number generation

In [28]:
# we have random in np
np.random.rand(5)
# 5 random elements between 0 and 1
# 0 and 1 is normalization
# between -3 and 3 is standardization

array([0.75815505, 0.42017925, 0.19567096, 0.62128209, 0.52073856])

In [29]:
np.random.randn(10)
#standardization between -3 and 3

array([ 0.35853892, -1.40041051, -0.19462095,  0.11031443,  1.72026154,
        1.38931493,  0.97925864,  0.05032809, -0.56370004, -1.33594225])

In [30]:
np.random.randint(6)
# generate a random number between 0 and 6

3

In [31]:
np.random.randint(10,20,10)
# between range 10 and 20 generate 10 random numbers

array([15, 15, 12, 11, 14, 11, 12, 13, 15, 10], dtype=int32)

### Array Attributes

In [32]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
arr.shape
# attribute hai to no parenthesis
# (rows,cols)

(3, 3)

In [34]:
arr.size
# no. of elements

9

In [35]:
arr.dtype
# datatypes

dtype('int64')

### Array methods

In [36]:
arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
arr.min()
# index of the minimum element np.int64(1)

np.int64(1)

In [38]:
arr.max() #np.int64(9) 9th element

np.int64(9)

In [39]:
arr.sum() #np.int64(45) sum of all elements

np.int64(45)

In [40]:
np.sum(arr,axis=0)
#column-wise sum axis =0
#row-wise sum axis =1


array([12, 15, 18])

In [41]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [42]:
arr.mean() #np.float64(5.0)

np.float64(5.0)

In [43]:
arr.std() # standard deviation

np.float64(2.581988897471611)

In [44]:
arr.argmax()
# 9th element index 8 is min therefore output np.int64(8)

np.int64(8)

In [45]:
arr.argmin() #np.int64(0)

np.int64(0)

### Reshaping and Resizing

In [46]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [47]:
arr = arr.reshape(6,5)
# 6 rows and 5 columns
# arranged row-wise 
#array([[ 1,  2,  3,  4,  5],
       #[ 6,  7,  8,  9, 10],
       #[11, 12, 13, 14, 15],
       #[16, 17, 18, 19, 20],
       #[21, 22, 23, 24, 25],
       #[26, 27, 28, 29, 30]])

In [48]:
arr.resize(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

### Numpy Indexing and Slicing Of Vector


In [49]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [50]:
arr[3]
#indexing from 0 

np.int64(14)

In [51]:
# slicing
# get 12,13,14,15
arr[1:5:1]

array([12, 13, 14, 15])

In [52]:
arr[:5]
# first value is 0
# 11,12,13,14,15

array([11, 12, 13, 14, 15])

In [53]:
arr[:]
# complete array

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [54]:
arr[3:]
# third to end

array([14, 15, 16, 17, 18, 19, 20])

In [55]:
arr[3::2]
# 2 steps

array([14, 16, 18, 20])

### Numpy index and slicing of matrix

In [56]:
arr = np.arange(1,31).reshape(6,5)

In [57]:
arr[0] #array([1, 2, 3, 4, 5])
# first row
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [58]:
arr[0][0] #np.int64(1)

np.int64(1)

In [59]:
arr[0,0] #np.int64(1)

np.int64(1)

In [60]:
arr[2,2]

np.int64(13)

In [61]:
# slicing
# 0,1 row and 1,2 col

arr[0:2 , 1:3]
#array([[2, 3],
       #[7, 8]])

array([[2, 3],
       [7, 8]])

In [62]:
arr[3:6 , 3:5]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [63]:
arr[:,2]
#all rows and 2nd col

array([ 3,  8, 13, 18, 23, 28])

### Boolean Indexing

In [64]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [65]:
bool_index = arr%2 == 0
bool_index
#array([False,  True, False,  True, False,  True, False,  True, False,
        #True])

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [66]:
arr = arr[bool_index]
arr
#array([12, 14, 16, 18, 20])

array([12, 14, 16, 18, 20])

### Array Operations

#### Arithematic operations

In [67]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
a1

array([1, 2, 3, 4, 5])

In [68]:
a2

array([ 6,  7,  8,  9, 10])

In [69]:
arr2 = a1 + a2
#element-wise additon with arrays with same no. of elements
arr2

array([ 7,  9, 11, 13, 15])

In [70]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [71]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [72]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [73]:
a1//a2

array([0, 0, 0, 0, 0])

In [74]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

In [75]:
l = [10,20,30,40]
arr = np.array(l)

In [76]:
for i in l:
    print(i+10)

20
30
40
50


In [77]:
# broadcasting saare array kai elements mai +10
arr+10

array([20, 30, 40, 50])

In [78]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [79]:
arr2 + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

#### Deep copy and Shallow copy

In [80]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [81]:
slice = a[:5]
slice

array([1, 2, 3, 4, 5])

In [82]:
slice = slice*10

In [83]:
slice

array([10, 20, 30, 40, 50])

In [84]:
a
# no change in a there was a change in slice but not
# in a
# shallow copy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [85]:
b=a
# deep copy as if b changes a also changes

In [86]:
b[0]=99

In [87]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [88]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [89]:
c=a.copy()
# shallow copy if change in c no change in a

In [90]:
c[0]=1

In [91]:
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [92]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

#### Matrix Operations

In [93]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])


In [94]:
A

array([[1, 2],
       [3, 4]])

In [95]:
B

array([[5, 6],
       [7, 8]])

In [96]:
A*B
# element wise multiplication not matrix multiplication

array([[ 5, 12],
       [21, 32]])

In [97]:
A @ B
# matrix multiplication row by column

array([[19, 22],
       [43, 50]])

In [98]:
np.dot(A,B)
# same as A @ B

array([[19, 22],
       [43, 50]])

In [99]:
A

array([[1, 2],
       [3, 4]])

In [100]:
np.transpose(A)
# row becomes column

array([[1, 3],
       [2, 4]])

In [101]:
A.T
# same as np.transpose(A)

array([[1, 3],
       [2, 4]])

#### Advanced array manipulation

##### stacking Array

In [104]:

a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [115]:
np.vstack((a,b))# vertical stack
#array([[1, 2, 3, 4],
#       [5, 6, 7, 8]])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [116]:
np.hstack((a,b))# horizontal stack
#array([1, 2, 3, 4, 5, 6, 7, 8])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [117]:
np.column_stack((a,b))
#array([[1, 5],
#       [2, 6],
 #      [3, 7],
 #      [4, 8]])


array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

#### splitting array

In [118]:
c = np.arange(16).reshape(4,4)

In [119]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [122]:
np.hsplit(c,2)# horizontal split
#[array([[ 0,  1],
 #       [ 4,  5],
  #      [ 8,  9],
   #     [12, 13]]),
 #array([[ 2,  3],
  #      [ 6,  7],
   #     [10, 11],
    #    [14, 15]])]
#split based upon columns

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [125]:
a = np.vsplit(c,2)# vertical split
#[array([[0, 1, 2, 3],
#        [4, 5, 6, 7]]),
#array([[ 8,  9, 10, 11],
#       [12, 13, 14, 15]])]

In [126]:
for i in a:
    print(i)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


#### Valid Sudoku

In [127]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [128]:
s

array([[5, 3, 4, 6, 7, 8, 9, 1, 2],
       [6, 7, 2, 1, 9, 5, 3, 4, 8],
       [1, 9, 8, 3, 4, 2, 5, 6, 7],
       [8, 5, 9, 7, 6, 1, 4, 2, 3],
       [4, 2, 6, 8, 5, 3, 7, 9, 1],
       [7, 1, 3, 9, 2, 4, 8, 5, 6],
       [9, 6, 1, 5, 3, 7, 2, 8, 4],
       [2, 8, 7, 4, 1, 9, 6, 3, 5],
       [3, 4, 5, 2, 8, 6, 1, 7, 9]])

In [137]:
# sum of all rows is 45 and also for columns as
# 1+2+3+4+5+6+7+8+9 = 45
l1 = np.sum(s,axis = 0)
for i in l1:
    if i!=45:
        print("Not a valid sudoku for columns")
        break
else:
    print("Valid sudoku for columns")

Valid sudoku for columns


In [139]:
l2 = np.sum(s,axis = 1)
for i in l2:
    if i!=45:
        print("Not a valid sudoku for rows")
        break
else:
    print("Valid sudoku for rows")

Valid sudoku for rows


In [ ]:
# check in 3X3 block 

In [140]:
s[0:3 , 0:3]

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [141]:
s[0:3 , 3:6]

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [142]:
s[0:3 , 6:9]

array([[9, 1, 2],
       [3, 4, 8],
       [5, 6, 7]])

In [143]:
s[3:6 , 0:3]

array([[8, 5, 9],
       [4, 2, 6],
       [7, 1, 3]])

In [144]:
s[3:6 , 3:6]

array([[7, 6, 1],
       [8, 5, 3],
       [9, 2, 4]])

In [145]:
s[3:6 , 6:9]

array([[4, 2, 3],
       [7, 9, 1],
       [8, 5, 6]])

In [146]:
s[6:9 , 0:3]

array([[9, 6, 1],
       [2, 8, 7],
       [3, 4, 5]])

In [147]:
s[6:9 , 3:6]

array([[5, 3, 7],
       [4, 1, 9],
       [2, 8, 6]])

In [148]:
s[6:9 , 6:9]

array([[2, 8, 4],
       [6, 3, 5],
       [1, 7, 9]])

In [157]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n = (s[i : i+3 , j : j+3 ])
        print((n.sum()))


45
45
45
45
45
45
45
45
45


#### General Questions

In [210]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [211]:
# Get the shape of the matrix.
data.shape

(5, 3)

In [212]:
#Find the average age of students
n = (data[:,0])
sum=0
for i in n:
    sum+=i
print(sum / len(n))

18.4


In [213]:
#Find the average age of students
np.mean(data[:,0])

np.float64(18.4)

In [214]:
#Extract Math marks of all students.
print(data[:,1])
print(np.mean(data[:,1]))


[85 92 76 65 90]
81.6


In [215]:
#Find the highest Science mark.
m = data[:,2]
print(m.max())

95


In [216]:
np.max(data[:,2])

np.int64(95)

In [217]:
#Get details of the student who scored more than 90 in Math.
data[data[:,1]>90]
    

array([[19, 92, 88]])

In [218]:
#Increase Math marks of all students by 5.
data[:,1]+=5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [219]:
#Find how many students are younger than 19.
print(data[:,0]<19)
print(data[data[:,0]<19])
print(len(data[data[:,0]<19]))


[ True False  True  True False]
[[18 90 78]
 [17 81 95]
 [18 70 70]]
3


In [220]:
#Calculate the average marks in each subject (column-wise mean).
print(f"{np.mean(data[:,1], axis = 0)} are average maths marks")
print(f"{np.mean(data[:,2], axis = 0)} are average science marks")


86.6 are average maths marks
83.2 are average science marks


In [221]:
#Get data of students who scored at least 80 in both subjects.
print(data[:,1]>=80)
print(data[:,2]>=80)

data[(data[:,1]>=80) & (data[:,2]>=80)]# here & diff.

[ True  True  True False  True]
[False  True  True False  True]


array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [222]:
#Replace all Science marks < 75 with 0.
data[:,2]<75

array([False, False, False,  True, False])

In [223]:
data[:,2][data[:,2]<75]=0

In [224]:
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])